//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCate
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescuentosPorCantidad
    {
        public int DescuentoID { get; set; }
        public int CantidadMinima { get; set; }
        public decimal PorcentajeDescuento { get; set; }
    }
}
