//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCate
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViajesRealizados
    {
        public int ViajeID { get; set; }
        public Nullable<int> TourID { get; set; }
        public System.DateTime FechaViaje { get; set; }
    
        public virtual Tours Tours { get; set; }
    }
}
